schema_version = "1.0.0"

id = "Quick_Uv_Map"
version = "1.3.0"
name = "Quick Uv Map"
tagline = "UV2 Fast!"
maintainer = "Matty"
type = "add-on"


tags = ["UV"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
license = ["SPDX:GPL-2.0-or-later"]